### ISSUE TITLE
Webm support

### ISSUE THREAD

**Issue by b2kdaman** [iqnivek/save_tabbed_images#36]
Thanks a lot for this amazing extension)
I was wondering if you're going to add webm support? I can make a pull request with this feature. 
Too lazy to download this repo and get to know how React works(

**Comment by blurymind** [comment]
can you put up some instructions on debugging the extension's source code with chrome?

**Comment by iqnivek** [comment]
@blurymind sure thing, but please keep your comments on-topic or create a new issue, as debugging isn't related to webm support.

@b2kdaman webm support doesn't seem unreasonable, but I don't think I'll be adding it at least for the time being, sorry! Enabling webm-saving by default would be an unexpected behavior given the name of the extension, so it'd be better to have it be a configurable option, but then it'd be hard to discover, and I'm not sure a lot of people would be looking for that functionality in any case. But if a file extension picker gets added in the future, then this could be an easy add. Thanks for the suggestion though!
