### ISSUE TITLE
Add option to isolate images into tabs in the first place

### ISSUE THREAD

**Issue by Moscarda** [iqnivek/save_tabbed_images#41]
i use the following to automatically open a thumbnail clicked in Google Image Search directly in a new tab at full size:
[<img src="https://user-images.githubusercontent.com/8745569/29589657-0e81c3be-8764-11e7-9132-dec09f49ea82.png">](https://chrome.google.com/webstore/detail/straight-to-full-size-for/ghhmhdkbiodiengmhbbpjkcjodingned)
...and I was curious if the same functionality could be added to your extension, so one wouldn't require both?  That extension only works with Google Images, but it would amazing if you could give users the option to whitelist other domains/criteria in which images should be opened directly in their own tabs.

**Comment by iqnivek** [comment]
hmm, that'd be cool for sure, but it's not exactly part of what this extension was intended for, sorry! It seems like that extension would work fine separate from this one, though.
